#define FILE_VERSION        1,4,2,2
#define STR_FILE_VERSION   "1,4,2,2\0"
#define STR_FILE_VERSION2  "1.4.2.2"
#define STR_DATE           "30 Oct 2023\0"
#define NOMFENETRE    "VDT2BMP v" STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
