#define FILE_VERSION        1,5,1,1
#define STR_FILE_VERSION   "1,5,1,1\0"
#define STR_FILE_VERSION2  "1.5.1.1"
#define STR_DATE           "16 May 2024\0"
#define NOMFENETRE    "VDT2BMP v" STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
